### ISSUE TITLE
Timegal & Ninja Hayate Sound / Shutdown issues

### ISSUE THREAD

**Issue by HoJo215** [DirtBagXon/singe#1]
Only these two games seem to have this issue. The sound is off sync and fast.
When I go to push the start button, the games shutdown with the error below.

`h@h-NUC8i7BEH:~/.daphne$ '/home/h/.daphne/singe.sh' hayate
Singe Launcher : Script dir is /home/h/.daphne
--SINGE DAPHNE engine 1.0.11.1
--Command line is: ./singe.bin /home/h/.daphne/singe/hayate/hayate.singe -framefile /home/h/.daphne/singe/hayate/hayate.txt -homedir /home/h/.daphne -datadir /home/h/.daphne -sound_buffer 2048 -volume_nonvldp 5 -volume_vldp 30 -x 800 -y 600 
--CPU : Intel(R) 2600 MHz || Mem : 32000 megs
--OS : Linux 5.5 || Video : Intel Corporation Device 3ea5 (rev 01)
--OpenGL: Compiled In
--RGB2YUV Function: C
--Line Blending Function: C
--Audio Mixing Function: C
Setting alternate home dir:
/home/h/.daphne
/home/h/.daphne/singe/hayate/hayate.singe
Setting sound buffer size to 2048
Setting screen width to 800
Setting screen height to 600
Set 800x600 at 32 bpp with flags: 0
Initializing sound system ... 
Loading 'grumble.wav' failed...
Joystick #0 was successfully opened
Looking for: singeinput.ini
Remapping input ...
Framefile parse succeeded. Video/Audio directory is: /home/h/.daphne/singe/hayate/./
YUV overlay is done in software (ie unaccelerated).
Booting ROM ...
Starting Singe version 1.18
Search to 37310 received [blocking] 
Play
Successfully changed speed to 1/1X
Search to 3 received [blocking] 
Play
Pause
Search to 10 received [blocking] 
Play
Successfully changed speed to 1/1X
SINGE: Game Settings Loaded.
SINGE: Initializing Ninja Hayate Singe v1.1
Search to 1400 received [blocking] 
Play
Successfully changed speed to 1/1X
Search to 1240 received [blocking] 
Play
Successfully changed speed to 1/1X
SINGE: Script Error!
SINGE: error running function 'onOverlayUpdate': hayate.lua:1829: attempt to perform arithmetic on a nil value
SINGE: Script Error!
/home/h/.daphne/singe.sh: line 58: 21725 Segmentation fault      (core dumped) ./$SINGE_BIN $DAPHNE_SHARE/singe/$1/$1.singe $FULLSCREEN -framefile $DAPHNE_SHARE/singe/$1/$1.txt -homedir $DAPHNE_SHARE -datadir $DAPHNE_SHARE -sound_buffer 2048 -volume_nonvldp 5 -volume_vldp 30 -x 800 -y 600
Loader failed with an unknown exit code : 139.
`

Any idea whats going on?

**Comment by DirtBagXon** [comment]
Heya, these are the only two games that use compiled LUA bytecode in the .singe file.

I had issues getting these running, and added some *kludges* to get a 64bit system to read these 32bit bytecode files, these *fixes* are included in the repo. However, I did not try this on kernel 5.x kernel I see you are running.

I have managed to decompile versions of these .singe files which would be a good starting point for a remedy.... 

I will push them to the bytecode folder of this repo.

Backup your originals, then `mv timegal.singe.decompiled timegal.singe` etc...

**Comment by DirtBagXon** [comment]
Heya, these are the only two games that use compiled LUA bytecode in the .singe file.

I had issues getting these running, and added some *kludges* to get a 64bit system to read these 32bit files, which is included in the repo. However, I did not try this on kernel 5.x kernel I see you are running.

I have the decompiled versions of these .singe files which would be a good starting point for a remedy....

**Comment by DirtBagXon** [comment]
This error is also detailed in the **bytecode** directory of this repo:

"SINGE: Script Error! SINGE: error running function 'onOverlayUpdate': hayate.lua:1829: attempt to perform arithmetic on a nil value SINGE: Script Error! /home/h/.daphne/singe.sh: line 58: 21725 Segmentation fault (core dumped)"

Try the replacement .singe file there....

**Comment by HoJo215** [comment]
I can confirm the .singe file replacement fixed the shutdown issue.

The sound issue is still present though. 
It's out of sync where the audio plays before the scene actually occurs.

**Comment by DirtBagXon** [comment]
Interesting.... I wonder if this is still a **bytecode** issue as all other games are not exhibiting the issue. Also, I note you are on kernel 5.x and Intel graphics, so possibly another avenue.

Can you give a rundown of your setup and architecture please?

I managed to decompile the bytecode to fix the issues detailed in the README.  I will upload the decompiled versions into the same directory in the repo, can you try those to see if it helps?

You will need to rename accordingly to .singe and overwrite current files again.

**Comment by HoJo215** [comment]
Intel NUC 8i7BEH  

i7-8559U Processor (8M Cache, up to 4.50 GHz)
Intel Iris 655 integrated graphics
32gb of ram

Ubuntu 18.04.4 (5.5.7 mainline kernel)
Padoka Mesa 20.00-dev

My original Daphne-Singe setup is the original windows release through wine cmd.
That worked wonders other than quick .bat pop up.

I bumped into this and decided to test it out.

Daphne works great besides trying to figure how to run Dragons Lair and Space Ace Enhanced versions without creating new folders, doubling the space..

Singe works well except these two games.
Daphne integrated Singe plays fine now with your .singe fix files.

It's just your 118 stand alone that has the audio problem now.
Maybe something off in the libsinge.so or the launcher script?

**Comment by DirtBagXon** [comment]
"Daphne works great besides trying to figure how to run Dragons Lair and Space Ace Enhanced versions without creating new folders, doubling the space.." - Use symlinks :)

When you state "Daphne integrated Singe plays fine" - from mine or David's repo? 

The same patches to singe are applied to both Daphne and standalone singe, so it may be a change in the 1.18 codebase somewhere....

**Comment by HoJo215** [comment]
I'm compiling. I compiled both of them just now to avoid confusion and ran them.
Both. Yours and David's integrated Singe works great now with your .singe fixes.

So it has to be the codebase then. I'm sure you'll iron it out at some point.. and just to be creepy..
I'm following you. lol

Thanks for the tip :)

**Comment by DirtBagXon** [comment]
Need to try and replicate it now then....

`YUV overlay is done in software (ie unaccelerated).` 
 vs
`YUV overlay is hardware accelerated.`

Mmmm.. so a few avenues to explore....

**Comment by DirtBagXon** [comment]
Ok - fixed I believe, resolution is around:

`Loading 'grumble.wav' failed`

Place the `sound/grumble.wav `file into` ~/.daphne/sounds`

I should error out on that failure, seems to be reproducible this side... can you confirm?. 

I guess you didn't:  `cp -a pics sound ~/.daphne/` due to existing installation.....

**Comment by DirtBagXon** [comment]
Ok - fixed I believe, resolution is around:

`Loading 'grumble.wav' failed`

Place the `sound/grumble.wav `file into` ~/.daphne/sound`

I should error out on that failure, seems to be reproducible this side... can you confirm?. 

I guess you didn't:  `cp -a pics sound ~/.daphne/` due to existing installation.....

**Comment by HoJo215** [comment]
Bingo! You are correct sir. 118 is working and in-sync now.
I forgot all about the grumble.wav as you said, due to previous installation.

On that note. I will close this as the solution is all here.
Thanks for taking the time to help me out. It's appreciated.
