### ISSUE TITLE
Singe API mismatch when using terminal commands

### ISSUE THREAD

**Issue by HoJo215** [DirtBagXon/singe#2]
Its me again.
So I'm creating script launchers for each game to hook into retropie's front end.
Everything runs fine with you script launcher from terminal but when I run mine, there's mixed results..

For games where everything is in the root folder I can use inside a script:

/home/h/.daphne/singe.sh -fullscreen game

It loads fine but the others with video sub folders can't find the .singe and .txt files.

`
h@h-NUC8i7BEH:~/.daphne$ '/opt/retropie/emulators/daphne/games/MadDog.sh' 
Singe Launcher : Script dir is /home/h/.daphne

.singe ?file: /home/h/.daphne/singe/maddog
.txt ?g       /home/h/.daphne/singe/maddog
`

So I tried full path commands and I receive Singe API mismatch.

`h@h-NUC8i7BEH:~/.daphne$ ./singe.bin '/home/h/.daphne/singe/chantze/chantze.singe' 
--SINGE DAPHNE engine 1.0.11.1
--Command line is: ./singe.bin /home/h/.daphne/singe/chantze/chantze.singe 
--CPU : Intel(R) 2600 MHz || Mem : 32000 megs
--OS : Linux 5.5 || Video : Intel Corporation Device 3ea5 (rev 01)
--OpenGL: Compiled In
--RGB2YUV Function: C
--Line Blending Function: C
--Audio Mixing Function: C
/home/h/.daphne/singe/chantze/chantze.singe
Set 640x480 at 32 bpp with flags: 0
Initializing sound system ... 
WARNING : requested 2048 samples for sound buffer, but got 1024 samples
Joystick #0 was successfully opened
Looking for: singeinput.ini
Remapping input ...
Framefile parse succeeded.
Video/Audio directory is: /home/h/.daphne/singe/chantze/./
YUV overlay is done in software (ie unaccelerated).
Singe API version mismatch!  Something needs to be recompiled...
Shutting down sound system...
Shutting down video display...
`

I made sure both .singe and .txt files are named after the game folder too.
Both singe.bin and libsinge.so are from the same build. 
I'm not to sure what going on here. Any ideas?

**Comment by DirtBagXon** [comment]
Hey,

OK, so within each directory, you have a main binary (in this repo case **singe.bin**, in the daphne repo its called **daphne.bin**) and within each directory there are also a couple of shared libraries (**libsinge.so** & l**ibvldp2.so**). These shared libraries are linked to the main binary API at compile time, which is versioned. _So each of these shared libraries will only work with the binary it was compiled against._

The startup script, combats this issue using the `LD_LIBRARY_PATH` environment variable to tell the main binary the location of the shared libraries it should load:

`export LD_LIBRARY_PATH=$SCRIPT_DIR:$DAPHNE_SHARE:$LD_LIBRARY_PATH`

You must be specifying a bad PATH for the incorrect shared library in your startup script.

Be aware that the shell script will use the first instance it finds in the `LD_LIBRARY_PATH` in the **specified order**, So adding multiple locations for different library/binary versions will cause them to use the first one they find. This will cause the issue you are seeing, so you need to be specific on each game.

If all the variable names are confusing: `$SCRIPT_DIR:$DAPHNE_SHARE` etc, just **hardcode** them. BUT `$LD_LIBRARY_PATH` **must come last!!!**

`export LD_LIBRARY_PATH=$SCRIPT_DIR:$DAPHNE_SHARE:$LD_LIBRARY_PATH`

to (note separation by ':' colon)

`export LD_LIBRARY_PATH=/home/h/singe/location/oflibraries:/home/h/.daphne:$LD_LIBRARY_PATH`

Take a look at the top of the run.sh and singe.sh scripts on how it's currently done:

SCRIPT_DIR=`dirname "$0"`
DAPHNE_SHARE=~/.daphne

**Comment by DirtBagXon** [comment]
A quick debug,  add:

`echo $LD_LIBRARY_PATH` 

into your startup script just before it runs the binary, this will print out what environment the game is running against....

**Comment by HoJo215** [comment]
I have the launchers up running now thanks to your detailed explanation.
Funny thing is the daphne.bin still works with the singe build's libvldp2.so
and Ninja Hayate / Timegal doesn't need a LD_LIBRARY_PATH environment variable.

I guess that's what was throwing me through a loop.

Thanks again! This is awesome work your putting in.

**Comment by DirtBagXon** [comment]
Well technically the **libvldp2.so** library is the LaserDisc emulator library, which hasn't changed between releases, so that's why it works.

It's just easier to define them as different binary dependant releases in a post like this.

Ninja Hayate / Timegal have to be picking up the **libsinge.so** functions from somewhere, so you're providing them somehow, but I'll leave that as an exercise for the reader....

**Comment by HoJo215** [comment]
Okay so... ActionMax.  I followed your folder structure from the launcher. 
Everything looks good but when I run your launcher, it's not finding the videos in the root folder.
Screen loads, grumble.wav error about "could not open video: video_ActionMaxIntro.m2v"

![Screenshot from 2020-03-12 22-45-21](https://user-images.githubusercontent.com/61361264/76585265-53bce280-64b4-11ea-9b10-08432b0caca5.png)

**Comment by DirtBagXon** [comment]
I did mess around with the ActionMax structure to satisfy my OCD 8).
I also didn't provide the framefile changes for the structure and case changes:


**38ambushalley/frame_38ambushalley.txt**
```
.

1 ../video_actionmaxintro.m2v
355     video_38ambushalley.m2v
28175   ../video_menu.m2v
```


**bluethunder/frame_bluethunder.txt**
```
.

1       ../video_actionmaxintro.m2v
355     video_bluethunder.m2v
27950   ../video_menu.m2v
```

**hydrosub2021/frame_hydrosub2021.txt**
```
.

1       ../video_actionmaxintro.m2v
355     video_hydrosub2021.m2v
28820   ../video_menu.m2v
```

**popsghostly/frame_popsghostly.txt**
```
.

1       ../video_actionmaxintro.m2v
355     video_popsghostly.m2v
31835   ../video_menu.m2v
```

**sonicfury/frame_sonicfury.txt**
```
.

1       ../video_actionmaxintro.m2v
355     video_sonicfury.m2v
26645   ../video_menu.m2v
```

Thanks for finding all by documentation issues :+1:

**Comment by DirtBagXon** [comment]
I don't recall making changes to the other singe files, but if you can provide **emulator.singe** and **framework.singe** if you see further issues, it will save me having to reacquire the originals.

**Comment by HoJo215** [comment]
Well, I edited the framefiles and now there is a Singe script error. It can't find the emulator.singe file.
I think there might be some linux case sensitivity issues going on because I had to rename the videos to their original style " video_SonicFury.m2v " but I had to leave the .singe and frame .txt files lowercase. Take a look at this log on the compiling script error part.

`h@h-NUC8i7BEH:~/.daphne$ '/home/h/.daphne/actionmax.sh' sonicfury
ActionMax Launcher : Script dir is /home/h/.daphne
--SINGE DAPHNE engine 1.0.11.1
--Command line is: ./singe.bin /home/h/.daphne/singe/actionmax/sonicfury/sonicfury.singe -framefile /home/h/.daphne/singe/actionmax/sonicfury/frame_sonicfury.txt -homedir /home/h/.daphne -datadir /home/h/.daphne -volume_nonvldp 15 -volume_vldp 40 -x 800 -y 600 
--CPU : Intel(R) 2600 MHz || Mem : 32000 megs
--OS : Linux 5.5 || Video : Intel Corporation Device 3ea5 (rev 01)
--OpenGL: Compiled In
--RGB2YUV Function: C
--Line Blending Function: C
--Audio Mixing Function: C
Setting alternate home dir:
/home/h/.daphne
/home/h/.daphne/singe/actionmax/sonicfury/sonicfury.singe
Setting screen width to 800
Setting screen height to 600
Set 800x600 at 32 bpp with flags: 0
Initializing sound system ... 
WARNING : requested 2048 samples for sound buffer, but got 1024 samples
No joysticks detected
Looking for: singeinput.ini
Remapping input ...
Framefile parse succeeded.
Video/Audio directory is: /home/h/.daphne/singe/actionmax/sonicfury/./
YUV overlay is done in software (ie unaccelerated).
Booting ROM ...
Starting Singe version 1.18
SINGE: Script Error!
SINGE: error compiling script: cannot open singe/ActionMax/Emulator.singe: No such file or directory
Shutting down sound system...
Shutting down video display...`


Here goes the files you want. Take note that the Framework.singe file was originally located in a folder named " Singe " inside the actionmax folder.

.daphne/singe/ActionMax/Singe/Framework.singe

[singe_am.zip](https://github.com/DirtBagXon/singe/files/4330386/singe_am.zip)

**Comment by DirtBagXon** [comment]
OK, so I also edited the emulator.singe file for case and file locations too...

Firstly I changed all file names to lowercase, and from your screenshot above, I assume you did the same. If this has changed, please firstly change **emulator.singe** and any other files back to lowercase.

Secondly, you are correct **Framework.singe** was in a different directory, I moved that also and made lowercase. Again above you placed it as I did in the main directory, and it should be there and lowercase as per your screenshot. Ensure this is still the case.

Thirdly, make a backup of your current **emulator.singe**

Now, here is a diff file to patch your emulator.singe

[emulator_diff.zip](https://github.com/DirtBagXon/singe/files/4330756/emulator_diff.zip)

Unzip it, copy it into the directory with the current **emulator.singe** file and then run:

`patch -p0 < emulator.diff `

You should see:
`patching file emulator.singe`

Then try again.....

**Comment by DirtBagXon** [comment]
> I had to rename the videos to their original style " video_SonicFury.m2v " 

- This is dictated by the case of the filename in your framefile above:

I made them lowercase so, as per my file above.. 

```
1       ../video_actionmaxintro.m2v
355     video_sonicfury.m2v
26645   ../video_menu.m2v

```
You are free to do what you want, but make sure the actual filename and the name **in** the framefile match.

Windows users don't get this issue, but my OCD says uppercase filenames in Linux look wrong.... 8)

**Comment by HoJo215** [comment]
I have it! After a lot of framefile renaming and your emulator.singe patch.
I also had to edit and lowercase the following below in each AM game's .singe file:

dofile("singe/actionmax/emulator.singe")

**Comment by DirtBagXon** [comment]
`-fullscreen_window` displays at the correct aspect 4:3 ratio on my system.

`-fullscreen` stretches to the aspect ratio of the display, so is stretched horizontally on a 16:9 monitor (i.e. no black bars).

**Comment by HoJo215** [comment]
Black border was a bad choice of words. I should say a black outline box around the 4:3 frame.
This "outline box" was not present using the Windows Singe through wine.

**Comment by DirtBagXon** [comment]
![window_fullscreen](https://user-images.githubusercontent.com/28685555/76650957-853cb900-655b-11ea-8e41-56edbbfc7c68.png)

This is `-fullscreen_window` screenshot in Classic Gnome.
Yours sounds like a Window/Desktop manager theme issue....

**Comment by HoJo215** [comment]
Maybe because mine is the Remastered version. I don't have that loading screen.

Loading screen:
![Screenshot from 2020-03-13 15-30-42](https://user-images.githubusercontent.com/61361264/76653844-f53d4600-653f-11ea-8f88-14478cea6ed8.png)

Black outline box:
![Screenshot from 2020-03-13 15-28-06](https://user-images.githubusercontent.com/61361264/76653888-100fba80-6540-11ea-808b-f6312238f619.png)

**Comment by DirtBagXon** [comment]
Just to tie off this issue, I acquired the **remastered** version of: **timegal.m2v**

`sha1 8d86749a1019d699c0841ef2f146cd6885486735  timegal.m2v  - size 2103988858`

I saw the black border you are experiencing using -fullscreen_window.

`sha1 eedd487f1cdc70b2b2f08c14b3101118c2bac65e  timegal.m2v - size 2019095151`

Did NOT exhibit this issue.
